services:
  app:
    container_name: karage-app
    build: 
      context: .
      dockerfile: Dockerfile
              
    volumes:
      - ..:/code:cached
      - ~/.aspnet/https:/https:ro
      - ~/.aspnet/DataProtection-Keys:/home/vscode/.aspnet/DataProtection-Keys

    command: sleep infinity

  mailpit:
    image: 'axllent/mailpit:latest'
    restart: unless-stopped
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      SA_PASSWORD: P@ssw0rd
      ACCEPT_EULA: Y

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"  
  seq:
    image: datalust/seq:latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_ADMINPASSWORD: password
    ports:
      - "5340:80"
      - "5341:5341"

  prometheus:
    image: prom/prometheus:latest
    container_name: karage-prometheus
    restart: unless-stopped
    ports:  
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: karage-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-data:
