# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout: 10s # Global timeout for scraping targets

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'karage-api'
    scrape_interval: 10s # Poll every 10 seconds for responsive monitoring
    scrape_timeout: 5s # Timeout for individual scrapes
    metrics_path: '/metrics' # Default OpenTelemetry metrics endpoint
    scheme: 'https' # Use HTTPS as configured in devcontainer
    tls_config:
      insecure_skip_verify: true # Skip SSL verification for development certs
    static_configs:
      - targets: ["karage-app:5001"]  # Devcontainer app service and HTTPS port
        labels:
          service: 'karage-api'
          environment: 'development'
          application: 'karage-api'
    honor_labels: false
    honor_timestamps: true